import { StyleSheet } from 'react-native';
export const p = StyleSheet.create({
  faceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  faceOption: { width: '31%', paddingVertical: 8, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#E4DCEB', alignItems: 'center', justifyContent: 'center' },
  smallFace: { width: 64, height: 64, alignItems: 'center', justifyContent: 'center' },
  headerIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#EEE8F6', alignItems: 'center', justifyContent: 'center' },
  headerGlyph: { fontSize: 27, color: '#695080', fontWeight: '600' },
  pinnedPreview: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EEE8F6', borderRadius: 23, marginBottom: 12 },
  compactAvatar: { width: 132, height: 148, alignItems: 'center', justifyContent: 'center' },
  shopHeader: { paddingHorizontal: 24, paddingTop: 20, maxWidth: 600, width: '100%', alignSelf: 'center' },
  shopTabs: { flexDirection: 'row', gap: 8, marginBottom: 15 },
  shopTab: { flex: 1, minHeight: 69, backgroundColor: '#FFFFFF', borderRadius: 16, borderWidth: 2, borderColor: 'transparent', alignItems: 'center', justifyContent: 'center', padding: 6 },
  shopTabIcon: { color: '#80649F', fontSize: 22, marginBottom: 4 },
  shopGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12, marginBottom: 20 },
  shopTile: { width: '47%', flexGrow: 1, maxWidth: '49%', padding: 12, borderRadius: 20, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E9E1EF' },
  shopArt: { alignItems: 'center', justifyContent: 'center', backgroundColor: '#F7F3FA', borderRadius: 14, marginBottom: 12 },
  nav: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 17 },
  button: { backgroundColor: '#EEE8F6', paddingVertical: 12, paddingHorizontal: 16, borderRadius: 13, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  buttonText: { color: '#695080', fontWeight: '700', fontSize: 12 }, primary: { backgroundColor: '#80649F' }, primaryText: { color: '#FFFFFF' },
  selected: { borderWidth: 2, borderColor: '#80649F', backgroundColor: '#EEE8F6' }, disabled: { opacity: 0.45 },
  stats: { flexDirection: 'row', gap: 18, marginTop: 13 }, stat: { fontWeight: '700', color: '#6C577E', fontSize: 13 },
  modal: { flex: 1, backgroundColor: '#FAF8F5' }, modalContent: { padding: 24, maxWidth: 600, width: '100%', alignSelf: 'center', paddingBottom: 40 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 }, title: { fontSize: 24, fontWeight: '800', color: '#40314E', flex: 1 },
  preview: { alignItems: 'center', backgroundColor: '#EEE8F6', borderRadius: 23, paddingVertical: 14, marginBottom: 20 },
  input: { backgroundColor: '#FFFFFF', borderColor: '#DED3E8', borderWidth: 1, borderRadius: 12, padding: 14, color: '#40314E', fontSize: 16, marginBottom: 18 },
  options: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 20 }, option: { padding: 12, minWidth: 70, minHeight: 48, borderRadius: 13, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4DCEB', alignItems: 'center', justifyContent: 'center' },
  swatch: { width: 27, height: 27, borderRadius: 14, marginBottom: 7 }, item: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E9E1EF', padding: 16, borderRadius: 18, marginBottom: 12 },
  itemRow: { flexDirection: 'row', gap: 12, alignItems: 'center' }, itemTitle: { color: '#51435D', fontSize: 15, fontWeight: '700', marginBottom: 5 },
  badge: { color: '#6B8768', fontSize: 11, fontWeight: '700' }, progress: { backgroundColor: '#EEE8F6', height: 6, borderRadius: 3, marginTop: 12, overflow: 'hidden' }, progressFill: { backgroundColor: '#9B83BA', height: 6 },
});
